Algoritmo "AREA DO RETANGULO"

Var

base, altura, area, perimetro, diagonal: real


Inicio

escreval ("Digite a base do retangulo: ")
leia (base)
escreval ("Digite a altura do retangulo: ")
Leia (altura)

area <- base*altura

escreval ("A área é de: ", area:8:4)

perimetro <- 2*base+2*altura

escreval ("O perimetro é de:", perimetro:8:4)

diagonal <- raizq(exp(base, 2) + exp(altura, 2))

escreval ("A diagonal é de:", diagonal:8:4)






Fimalgoritmo