Algoritmo "Medidas"

Var

a, b, c, quadrado, triangulo, trapezio: real

Inicio

escreval ("Digite a medida A: ")
leia (a)
 
escreval ("Digite a medida B: ")
leia (b)
 
escreval ("Digite a medida C: ")
leia (c)
 
quadrado <- exp(a,2)
triangulo <- (a*b)/2
trapezio <- ((a+b)*c)/2
 
escreval ("Area do quadrado é: ", quadrado:6:4)

escreval ("Area do triangulo é: ", triangulo:6:4)

escreval ("Area do trapezio é: ", trapezio:6:4)

Fimalgoritmo