Algoritmo "Multiplos"

Var

x, y: inteiro
n, m: real

Inicio

escreval("Digite dois números inteiros:")
leia(x)
leia(y)

n <- x mod y
m <- Y mod x

se (x > y) e (n=0) entao   // Podia ter feito se (X mod y = 0) ou (y mod X = 0) entao
   escreva("São Multiplos")
senao
   se (y > x) e (m=0) entao
      escreva("São Multiplos")
   senao
      escreva("Não são Multiplos")

   fimse

fimse

















Fimalgoritmo